import { PhosphorIcon, Stars } from "@/components/phosphor-icon";
import Link from "next/link";
import { services, wa } from "@/lib/content";
import { FAQList } from "@/components/faq-list";
const reviews=[
  {name:"Lourdes David",text:"Serviço excelente, pontualidade e perfeição."},
  {name:"Edson Saiga Torre",text:"Sensacional, excelente qualidade e preço justo."},
  {name:"Laís Iozzi Saraiva",text:"Fiquei satisfeita indicarei com certeza muito bom o atendimento."},
];
export function Home(){return <main>
<section className="hero"><div className="hero-image"/><div className="hero-content"><span className="eyebrow">Vidraçaria em Santos · desde a Ponta da Praia</span><h1>O vidro certo<br/><em>muda tudo.</em></h1><p>Box, espelhos e soluções em vidro que valorizam a luz, a arquitetura e o seu dia a dia.</p><div className="hero-actions"><a className="button button-primary" href={wa} target="_blank" rel="noreferrer">Solicitar avaliação <span><PhosphorIcon name="arrow-up-right" size={16}/></span></a><Link className="button button-quiet" href="/servicos">Conhecer soluções</Link></div><div className="hero-proof"><span className="rating"><Stars/> <b>5,0</b></span><span>no Google · 13 avaliações</span></div></div><div className="hero-caption">VIDRO TEMPERADO · SANTOS / SP</div></section>
<section className="trust-strip"><div><span className="trust-number">01</span><strong>Atendimento local</strong><small>Ponta da Praia · Santos</small></div><div><span className="trust-number">02</span><strong>Soluções sob medida</strong><small>Avaliação conforme o ambiente</small></div><div><span className="trust-number">03</span><strong>Contato direto</strong><small>Converse com a equipe pelo WhatsApp</small></div></section>
<section className="section services-section"><div className="section-intro split"><div><span className="eyebrow">O que fazemos</span><h2>Transparência em cada escolha.</h2></div><p>Do box ao espelho, cada aplicação pede uma leitura própria do espaço. Conheça as soluções da VidroTemper.</p></div><div className="service-grid">{services.map((s,i)=><Link className="service-card" href={`/${s.slug}`} key={s.slug}><span className="service-index">0{i+1}</span><span className="service-icon"><PhosphorIcon name={s.icon} size={40}/></span><span className="service-kicker">{s.kicker}</span><h3>{s.title}</h3><span className="card-link">Explorar solução <span><PhosphorIcon name="arrow-up-right" size={16}/></span></span></Link>)}</div></section>
<section className="feature-band"><div className="feature-image" role="img" aria-label="Box de vidro em um banheiro contemporâneo"/><div className="feature-copy"><span className="eyebrow">Um espaço mais leve</span><h2>O detalhe que deixa a luz passar.</h2><p>O vidro conecta áreas, valoriza materiais e deixa o ambiente respirar. A escolha começa pelo que faz sentido na sua casa.</p><Link className="text-link" href="/projetos">Ver possibilidades <span><PhosphorIcon name="arrow-up-right" size={16}/></span></Link></div></section>
<section className="section process-section"><div className="section-intro"><span className="eyebrow">Como começamos</span><h2>Do primeiro contato à solução.</h2></div><div className="process-grid"><article><b>01</b><h3>Conte o que precisa</h3><p>Explique o serviço e onde será feito.</p></article><article><b>02</b><h3>Envie fotos e medidas</h3><p>Uma referência inicial ajuda a entender o espaço.</p></article><article><b>03</b><h3>Avalie as opções</h3><p>A equipe orienta o próximo passo e confirma a necessidade de visita.</p></article></div></section>
<section className="google-reviews" id="avaliacoes" aria-labelledby="reviews-title"><div className="reviews-heading"><div><span className="google-wordmark" aria-label="Google"><b>G</b><i>o</i><em>o</em><b>g</b><strong>l</strong><i>e</i></span><span className="eyebrow">Avaliações de clientes em Santos</span><h2 id="reviews-title">Experiências reais,<br/>no jeito Google de avaliar.</h2></div><div className="google-score"><strong>5,0</strong><span className="google-stars" aria-label="5 de 5 estrelas"><Stars/></span><small>13 avaliações no Google</small><a href="https://share.google/sFcAfVwApf2M1fmzg" target="_blank" rel="noreferrer">Ver todas no Google <PhosphorIcon name="arrow-up-right" size={16}/></a></div></div><div className="google-review-grid">{reviews.map((review)=><article className="google-review-card" key={review.name}><div className="review-author"><span className="review-avatar" aria-hidden="true">{review.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><div><strong>{review.name}</strong><small>Avaliação no Google</small></div><span className="mini-google" aria-hidden="true">G</span></div><div className="google-stars" aria-label="5 de 5 estrelas"><Stars/></div><p>“{review.text}”</p><span className="verified-review">Comentário público no perfil da VidroTemper em Santos</span></article>)}</div><p className="reviews-note">Nota e quantidade exibidas conforme o perfil da VidroTemper no Google. As avaliações podem mudar.</p></section>
<section className="section service-area"><div><span className="eyebrow">Onde estamos</span><h2>VidroTemper em Santos.</h2><p>Av. Dr. Pedro Lessa, 578<br/>Ponta da Praia · Santos – SP</p><p className="muted">Consulte atendimento em São Vicente, Praia Grande e Guarujá.</p><a className="text-link" href="https://maps.google.com/?q=Av.+Dr.+Pedro+Lessa,+578,+Santos,+SP" target="_blank" rel="noreferrer">Abrir rota no mapa <span><PhosphorIcon name="arrow-up-right" size={16}/></span></a></div><div className="map-frame"><iframe title="Mapa da VidroTemper na Ponta da Praia, Santos" src="https://maps.google.com/maps?q=Av.%20Dr.%20Pedro%20Lessa%2C%20578%2C%20Santos%2C%20SP&t=&z=14&ie=UTF8&iwloc=&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></section>
<FAQList/><section className="closing-cta"><span className="eyebrow">Seu projeto começa com uma conversa</span><h2>Vamos encontrar a solução<br/>certa para o seu espaço?</h2><a className="button button-primary" href={wa} target="_blank" rel="noreferrer">Falar no WhatsApp <span><PhosphorIcon name="arrow-up-right" size={16}/></span></a></section>
</main>}
