export const wa = "https://wa.me/5513981028101?text=Ol%C3%A1%2C%20gostaria%20de%20solicitar%20uma%20avalia%C3%A7%C3%A3o%20com%20a%20VidroTemper.";
export const services = [
 {slug:"box-de-vidro",title:"Box de vidro",kicker:"Banheiro · sob medida",lead:"Mais leveza para o banheiro. Mais cuidado em cada detalhe.",body:"Um box bem especificado organiza o espaço, facilita a limpeza e deixa o ambiente visualmente mais amplo. A VidroTemper avalia as medidas, o tipo de abertura e o acabamento mais adequado para cada banheiro.",points:["Modelos de correr e de abrir, conforme o espaço","Vidros e ferragens definidos para a necessidade do ambiente","Orientação sobre medidas, instalação e manutenção"],icon:"shower"},
 {slug:"espelhos",title:"Espelhos",kicker:"Amplitude · luz · composição",lead:"Espelhos que ampliam a luz e dão intenção ao ambiente.",body:"Do espelho funcional ao elemento central da decoração, cada peça deve respeitar proporção, fixação e contexto. A avaliação considera o local de instalação e o resultado esperado.",points:["Espelhos para banheiros, halls, salas e espaços comerciais","Composição sob medida de acordo com o ambiente","Orientação de instalação e conservação"],icon:"rectangle"},
 {slug:"vidro-temperado",title:"Vidro temperado",kicker:"Residencial · comercial",lead:"Transparência e resistência para projetos bem resolvidos.",body:"O vidro temperado pode compor diferentes soluções arquitetônicas. A escolha da espessura, do acabamento e das ferragens depende das dimensões, da aplicação e das condições do local.",points:["Avaliação técnica conforme a aplicação","Opções para ambientes residenciais e comerciais","Acabamentos pensados para integrar o vidro ao projeto"],icon:"square-half"},
 {slug:"portas-e-janelas-de-vidro",title:"Portas e janelas de vidro",kicker:"Integração · luminosidade",lead:"Integre ambientes e aproveite melhor a luz natural.",body:"Portas e janelas de vidro criam continuidade visual e valorizam a iluminação. A solução certa parte de uma boa leitura do vão, do uso e das necessidades de cada imóvel.",points:["Soluções para áreas internas e externas","Avaliação do vão e da circulação","Detalhes de acabamento alinhados ao espaço"],icon:"door"},
 {slug:"manutencao-de-vidros",title:"Manutenção de vidros",kicker:"Ajuste · cuidado · segurança",lead:"Um ajuste no tempo certo evita que pequenos problemas cresçam.",body:"Folgas, desalinhamento e ferragens que perderam o ajuste merecem atenção. Descreva o que está acontecendo e envie fotos pelo WhatsApp para uma primeira orientação sobre o atendimento.",points:["Avaliação de box, portas e ferragens","Verificação de ajustes e condições de uso","Atendimento definido após entender o local e a necessidade"],icon:"wrench"}
];
export const faqs = [
 ["Quais serviços a VidroTemper oferece?","A VidroTemper trabalha com box de vidro, espelhos, vidro temperado, portas e janelas de vidro e manutenção de vidros. Envie sua necessidade pelo WhatsApp para confirmar o escopo e a disponibilidade."],
 ["A VidroTemper atende em Santos?","Sim. O endereço informado é na Av. Dr. Pedro Lessa, 578, Ponta da Praia, Santos. Também consulte atendimento em São Vicente, Praia Grande e Guarujá."],
 ["Como peço um orçamento?","Chame no WhatsApp pelo número (13) 98102-8101. Se puder, envie fotos, medidas aproximadas e o bairro. A equipe orienta os próximos passos."],
 ["O orçamento pode ser feito só com fotos?","Fotos ajudam a entender a solicitação, mas a confirmação das medidas e da solução pode exigir avaliação no local."],
 ["Qual é o prazo de instalação?","O prazo depende do tipo de serviço, das medidas e da disponibilidade de materiais e agenda. A VidroTemper informa o prazo após avaliar o pedido."],
 ["A VidroTemper tem avaliações no Google?","O perfil informado aparece com nota 5,0 e 13 avaliações. Consulte o perfil para ler as avaliações e ver atualizações."],
];
export const pages: Record<string,{title:string,kicker:string,lead:string,body:string,points:string[],service?:boolean}> = {
 "servicos":{title:"Soluções em vidro para cada ambiente",kicker:"Serviços VidroTemper",lead:"Escolha a solução. A gente ajuda a encontrar o melhor caminho para o seu espaço.",body:"Cada projeto começa entendendo o ambiente, o uso e as medidas. Converse com a VidroTemper para avaliar a solução mais adequada em Santos e região.",points:services.map(s=>s.title)},
 "box-de-vidro":{title:services[0].title,kicker:services[0].kicker,lead:services[0].lead,body:services[0].body,points:services[0].points,service:true},
 "espelhos":{title:services[1].title,kicker:services[1].kicker,lead:services[1].lead,body:services[1].body,points:services[1].points,service:true},
 "vidro-temperado":{title:services[2].title,kicker:services[2].kicker,lead:services[2].lead,body:services[2].body,points:services[2].points,service:true},
 "portas-e-janelas-de-vidro":{title:services[3].title,kicker:services[3].kicker,lead:services[3].lead,body:services[3].body,points:services[3].points,service:true},
 "manutencao-de-vidros":{title:services[4].title,kicker:services[4].kicker,lead:services[4].lead,body:services[4].body,points:services[4].points,service:true},
 "projetos":{title:"O vidro muda a sensação de um espaço",kicker:"Possibilidades de aplicação",lead:"Transparência, reflexo e luz natural podem redesenhar a forma de viver cada ambiente.",body:"Explore algumas aplicações comuns de vidro. As imagens desta página são referências visuais de ambientação; não representam obras realizadas pela VidroTemper. Para conhecer possibilidades no seu imóvel, fale com a equipe.",points:["Box de vidro para banheiros","Espelhos para ampliar e compor","Fechamentos e divisórias em vidro","Portas e janelas para integrar ambientes"]},
 "sobre":{title:"Vidro com cuidado em cada etapa",kicker:"Sobre a VidroTemper",lead:"Atendimento próximo, orientação clara e soluções pensadas para o espaço real.",body:"A VidroTemper atende em Santos a partir da Ponta da Praia, com soluções em box, espelhos, vidro temperado, portas, janelas e manutenção. Cada pedido é avaliado conforme o ambiente, as medidas e o uso esperado.",points:["Endereço em Ponta da Praia, Santos","Contato direto pelo WhatsApp","Atendimento residencial e comercial, conforme avaliação"]},
 "contato":{title:"Vamos conversar sobre seu projeto?",kicker:"Contato",lead:"Conte o que precisa, envie algumas fotos e receba orientação sobre os próximos passos.",body:"Fale com a VidroTemper pelo WhatsApp ou visite o endereço na Ponta da Praia. Para agilizar o atendimento, informe seu bairro e o tipo de serviço desejado.",points:["WhatsApp: (13) 98102-8101","Av. Dr. Pedro Lessa, 578 – Ponta da Praia, Santos – SP","Nota Google informada: 5,0 · 13 avaliações"]},
 "vidracaria-em-santos":{title:"Vidraçaria em Santos",kicker:"VidroTemper · Santos/SP",lead:"Box, espelhos, vidros temperados e manutenção com atendimento local.",body:"A VidroTemper fica na Ponta da Praia e recebe solicitações de toda Santos. Fale com a equipe para avaliar sua necessidade, confirmar atendimento no bairro e entender as opções para o seu imóvel.",points:["Ponta da Praia","Embaré e Aparecida","Boqueirão, Gonzaga e região","Consulte atendimento em São Vicente, Praia Grande e Guarujá"]}
};
