import { siteUrl } from "@/lib/site-url";
import { PhosphorIcon, Stars } from "@/components/phosphor-icon";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { pages, services, wa } from "@/lib/content";

export function generateStaticParams(){return Object.keys(pages).map((slug)=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=pages[slug];if(!page)return {};return {title:page.title,description:`${page.lead} VidroTemper em Santos, SP.`,alternates:{canonical:`/${slug}`}};}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug];if(!page)notFound();const service=page.service;const base=siteUrl;const crumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:base},{"@type":"ListItem",position:2,name:page.title,item:`${base}/${slug}`}]};const serviceSchema=service?{"@context":"https://schema.org","@type":"Service",name:page.title,description:page.body,provider:{"@type":"LocalBusiness",name:"VidroTemper",telephone:"+55 13 98102-8101",address:{"@type":"PostalAddress",streetAddress:"Avenida Doutor Pedro Lessa, 578",addressLocality:"Santos",addressRegion:"SP",postalCode:"11025-000",addressCountry:"BR"}},areaServed:{"@type":"City",name:"Santos"}}:null;
return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumb)}}/>{serviceSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceSchema)}}/>}<section className="inner-hero"><div className="inner-hero-glow"/><div className="inner-hero-copy"><div className="breadcrumbs"><Link href="/">Início</Link><span>/</span><span>{page.title}</span></div><span className="eyebrow">{page.kicker}</span><h1>{page.title}</h1><p className="lead">{page.lead}</p><p className="inner-body">{page.body}</p><a className="button button-primary" href={wa} target="_blank" rel="noreferrer">Conversar sobre meu projeto <span><PhosphorIcon name="arrow-up-right" size={16}/></span></a></div><div className="inner-hero-aside"><span className="glass-mark">V</span><small>VIDROTEMPER<br/>SANTOS · SP</small></div></section>
<section className="section detail-section"><div className="detail-heading"><span className="eyebrow">{service?"A solução":"Informações"}</span><h2>{service?"Pensado para o seu espaço.":page.title}</h2></div><div className="detail-list">{page.points.map((point,i)=><div key={point}><span>0{i+1}</span><p>{point}</p></div>)}</div></section>
{slug==="projetos"&&<section className="section visual-reference"><div className="visual-photo"/><div><span className="eyebrow">Referência visual</span><h2>Vidro em diálogo com arquitetura.</h2><p>Uma imagem conceitual para inspirar possibilidades. Cada projeto depende das medidas, do local e da especificação técnica.</p></div></section>}
{slug==="servicos"&&<section className="section services-section"><div className="service-grid">{services.map((s,i)=><Link className="service-card" href={`/${s.slug}`} key={s.slug}><span className="service-index">0{i+1}</span><span className="service-icon"><PhosphorIcon name={s.icon} size={40}/></span><span className="service-kicker">{s.kicker}</span><h3>{s.title}</h3><span className="card-link">Ver detalhes <span><PhosphorIcon name="arrow-up-right" size={16}/></span></span></Link>)}</div></section>}
{slug==="contato"&&<section className="section contact-details"><div><span className="eyebrow">WhatsApp</span><h2>(13) 98102-8101</h2><a className="text-link" href={wa} target="_blank" rel="noreferrer">Iniciar conversa <PhosphorIcon name="arrow-up-right" size={16}/></a></div><div><span className="eyebrow">Endereço</span><h2>Ponta da Praia · Santos</h2><p>Av. Dr. Pedro Lessa, 578<br/>Santos – SP · 11025-000</p><a className="text-link" href="https://maps.google.com/?q=Av.+Dr.+Pedro+Lessa,+578,+Santos,+SP" target="_blank" rel="noreferrer">Abrir no mapa <PhosphorIcon name="arrow-up-right" size={16}/></a></div></section>}
<section className="more-services"><div><span className="eyebrow">Continue explorando</span><h2>Mais soluções em vidro.</h2></div><div className="more-links">{services.filter(s=>s.slug!==slug).slice(0,3).map(s=><Link key={s.slug} href={`/${s.slug}`}>{s.title}<span><PhosphorIcon name="arrow-up-right" size={16}/></span></Link>)}</div></section><section className="closing-cta compact"><span className="eyebrow">VidroTemper · Santos</span><h2>Conte o que você precisa.</h2><a className="button button-primary" href={wa} target="_blank" rel="noreferrer">Chamar no WhatsApp <span><PhosphorIcon name="arrow-up-right" size={16}/></span></a></section></main>}
